module.exports = {
  xml: 'http://www.w3.org/XML/1998/namespace',
  rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
  owl: 'http://www.w3.org/2002/07/owl#',
  schema: 'http://schema.org/',
  xsd: 'http://www.w3.org/2001/XMLSchema#', // make sure that xsd prefix is present as we use it for typed dates
  sa: 'http://ns.sci.pe#',
  spdx: 'https://spdx.org/licenses/',

  // subjects
  subjects: 'http://ns.nature.com/subjects/',

  // sci.pe API
  user: 'https://sci.pe/user/',
  bot: 'https://sci.pe/bot/',
  tmp: 'https://sci.pe/tmp/',
  seq: 'https://sci.pe/seq/',
  service: 'https://sci.pe/service/',
  org: 'https://sci.pe/organization/',
  workflow: 'https://sci.pe/workflow/',
  journal: 'https://sci.pe/periodical/',
  graph: 'https://sci.pe/graph/',
  release: 'https://sci.pe/release/',
  action: 'https://sci.pe/action/',
  message: 'https://sci.pe/message/',
  email: 'https://sci.pe/email/',
  node: 'https://sci.pe/node/',
  anon: 'https://sci.pe/anon/',
  question: 'https://sci.pe/question/',
  answer: 'https://sci.pe/answer/',
  style: 'https://sci.pe/style/',
  styleNode: 'https://sci.pe/styleNode/',
  tag: 'https://sci.pe/tag/',
  order: 'https://sci.pe/order/',
  role: 'https://sci.pe/role/',
  audience: 'https://sci.pe/audience/',
  issue: 'https://sci.pe/issue/',
  audienceRole: 'https://sci.pe/audienceRole/',
  arole: 'https://sci.pe/arole/',
  srole: 'https://sci.pe/srole/',
  vendor: 'https://sci.pe/vendor/',
  customer: 'https://sci.pe/customer/',
  assigner: 'https://sci.pe/assigner/',
  participant: 'https://sci.pe/participant/',
  subscriber: 'https://sci.pe/subscriber/',
  offer: 'https://sci.pe/offer/',
  event: 'https://sci.pe/event/',
  scienceai: 'https://sci.pe/',
  scipe: 'https://sci.pe/',
  ses: 'https://sci.pe/ses/'
};
