module.exports = {
  xml: 'http://www.w3.org/XML/1998/namespace',
  rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
  owl: 'http://www.w3.org/2002/07/owl#',
  schema: 'http://schema.org/',
  xsd: 'http://www.w3.org/2001/XMLSchema#', // make sure that xsd prefix is present as we use it for typed dates
  sa: 'http://ns.science.ai#',
  spdx: 'https://spdx.org/licenses/',

  // subjects
  subjects: 'http://ns.nature.com/subjects/',

  // science.ai API
  user: 'https://science.ai/user/',
  bot: 'https://science.ai/bot/',
  tmp: 'https://science.ai/tmp/',
  seq: 'https://science.ai/seq/',
  service: 'https://science.ai/service/',
  org: 'https://science.ai/organization/',
  workflow: 'https://science.ai/workflow/',
  journal: 'https://science.ai/periodical/',
  graph: 'https://science.ai/graph/',
  release: 'https://science.ai/release/',
  action: 'https://science.ai/action/',
  message: 'https://science.ai/message/',
  email: 'https://science.ai/email/',
  node: 'https://science.ai/node/',
  question: 'https://science.ai/question/',
  answer: 'https://science.ai/answer/',
  style: 'https://science.ai/style/',
  styleNode: 'https://science.ai/styleNode/',
  tag: 'https://science.ai/tag/',
  order: 'https://science.ai/order/',
  role: 'https://science.ai/role/',
  audience: 'https://science.ai/audience/',
  issue: 'https://science.ai/issue/',
  audienceRole: 'https://science.ai/audienceRole/',
  vendor: 'https://science.ai/vendor/',
  customer: 'https://science.ai/customer/',
  assigner: 'https://science.ai/assigner/',
  participant: 'https://science.ai/participant/',
  subscriber: 'https://science.ai/subscriber/',
  offer: 'https://science.ai/offer/',
  event: 'https://science.ai/event/',
  scienceai: 'https://science.ai/',
  ses: 'https://scienceai/ses/'
};
